spring.application.name=order-flow

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=order-flow-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.blind.orderflow.shared.events.BaseEvent

spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true

# R2DBC MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/orderflow?sslMode=REQUIRED
spring.r2dbc.username=root
spring.r2dbc.password=

# Logging
logging.level.org.springframework.r2dbc=INFO
logging.level.reactor.netty.http.server=INFO
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %highlight(%-5level) %cyan([%thread]) %white([%X{correlationId:-N/A}]) %magenta(%logger{20}) | %msg%n

#mongo
spring.mongodb.uri=mongodb://localhost:27017/orderflow_menu

